### ISSUE TITLE
Error: Unable to resolve module react-native-paper

### ISSUE THREAD

**Issue by enieber** [rescript-react-native/paper#8]
## The problem

After create basic app with rescript-react-native I install this lib, but after compile the file `App.res` to `App.bs.js` is used the lib `react-native-paper` but not found this lib  and crash app.

### How to reproduce

Steps to reproduce:

1. create app with rescript-react-native
2. install lib follow doc
3. compile app
4. start app in mobile android

## Expected behavior

After compile lib the react-native find the react-native-paper or use the react-native-paper from bind rescript

## Actual behavior

Crash app because no found react-native-paper lib.

## Environment

libs install:

```
  "@rescript-react-native/paper": "^3.0.6",
  "@rescript/react": "^0.10.0",
  "react": "17.0.1",
  "react-native": "0.64.0",
  "rescript-react-native": "^0.64.3"
````

running in emulator android API_30

**Comment by enieber** [comment]
the code of app is open source:

https://github.com/enieber/libreflix-app

**Comment by MoOx** [comment]
You need to have `react-native-paper` installed as explained in the first line here https://github.com/rescript-react-native/paper#installation

**Comment by enieber** [comment]
thanks, is necessary to add `react-native-paper` version 3 because the new version of react-native-paper has an error when added.

**Comment by MoOx** [comment]
Yeah you need to be careful of the version to match the bindings. Also maybe this package should be updated...
